2015/03/16 20:33:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2015/03/16 20:34:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2015/03/16 20:38:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/03/16 20:38:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii/
---
2015/03/16 20:38:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2015/03/16 20:38:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index/gii".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('index/gii')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index/gii
---
2015/03/16 20:39:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1044] Access denied for user 'sigma'@'localhost' to database 'cms_sigma'' in C:\OpenServer\domains\ysigma.local\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\OpenServer\domains\ysigma.local\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\OpenServer\domains\ysigma.local\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\OpenServer\domains\ysigma.local\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\OpenServer\domains\ysigma.local\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\OpenServer\domains\ysigma.local\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\OpenServer\domains\ysigma.local\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\OpenServer\domains\ysigma.local\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\OpenServer\domains\ysigma.local\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\OpenServer\domains\ysigma.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\ysigma.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\ysigma.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/gii/model/index
HTTP_REFERER=http://ysigma.local/gii/default/index
---
2015/03/16 20:47:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\ysigma.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\ysigma.local\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\OpenServer\domains\ysigma.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
